version: '3'
services:
  web:
    container_name: feedback
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal

  db:
    container_name: feedbackDatabase
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: slaptazodis
    ports:
      - "3306:3306"